import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [loaded, setLoaded] = useState(false);
  console.log(loaded);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{ color: "red" }}>Next testing</h1>
        <div>
          <h3> {!loaded ? "Loading..." : ""}</h3>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            onLoad={() => setLoaded(true)}
            style={{ width: "100%", display: `${loaded ? "block" : "none"}` }}
            src="/images/banner.jpg"
            alt="banner-img"
          />
        </div>
      </main>
    </div>
  );
}
